### ISSUE TITLE
Multi User 

### ISSUE THREAD

**Issue by asepwaee** [oqhadev/waweb-phi#2]
Sy cba dari 2 browser dengan 2 akun whatsapp yg berbeda. Setelah keduanya berhasil login hanya salah satu yg bisa mengirim pesan lewat fungsi send messange/send img ? Apakah ada tipsnya agar kedua akun whatsapp bisa mengirim pesan berdasarkan akun masing-masing?

**Comment by oqhadev** [comment]
Duplicate of #1 
bisa dilihat disini penggunaan sederhananya
