### ISSUE TITLE
Can't resolve 'ws'

### ISSUE THREAD

**Issue by nusagates** [oqhadev/waweb-phi#3]
Gan, saya coba install ini pakai `yarn add waweb-phi` atau`npm install waweb-phi` di Laravel tapi kok error, ya?
Errornya begini:
`WARNING in ./node_modules/waweb-phi/src/Client.js 79:40-93
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/waweb-phi/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Error: Can't resolve 'ws' in 'C:\xampp\htdocs\etools\node_modules\puppeteer\lib'
 @ ./node_modules/puppeteer/lib/WebSocketTransport.js 16:18-31
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./node_modules/waweb-phi/src/Client.js
 @ ./node_modules/waweb-phi/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
`

Solusinya gimana, ya?  Mohon bantuannya.

**Comment by oqhadev** [comment]
bug ini ada di puppeter, bukan di library ini, coba cek di issue repo pupetternya
saya sarankan si install di directory yang terpisah, jangan disatukan dengan directory laravel 
karena digunakan oleh laravel mix, mungkin itu juga penyebab errornya

ref https://github.com/puppeteer/puppeteer/issues/3466
