### ISSUE TITLE
make screensize full

### ISSUE THREAD

**Issue by xiaorief** [oqhadev/waweb-phi#4]
edit file src/constants.js

add following line

exports.DefaultOptions = {
    puppeteer: {
        headless: false,
        **defaultViewport: null**
    },
    session: false,
    authTimeout: 10000,
}

**Comment by oqhadev** [comment]
not all want full screen, since all time run with headless 
and if you want full screen you can passing the option like this
```js
const client = new wa({
    puppeteer: { 
       headless: false, 
       defaultViewport: null
    },
    authTimeout: 30000,
});
```
